export const RODS = [
  {
    id: '001',
    name: 'Branch',
    rate: 50,
    multiplier: [10, 10, 10, 10, 8, 4, 2],
    uses: 5,
    color: 0xff7a00,
    image: 'rod-001',
    description: `Formed from a divine branch in a small village in the land of Lunacia!\n_All Lunacians will get this rod!_`,
  },
  {
    id: '002',
    name: 'Mavis',
    rate: 80,
    multiplier: [5, 15, 10, 10, 10, 8, 5],
    uses: 5,
    color: 0x3f74b5,
    image: 'rod-002',
    description: `A rod forged by the legendary Mavis!\n_Axie Collectors earned more than 3 Axie Owner roles will deserve this rod!_`,
  },
  {
    id: '003',
    name: 'BALD',
    rate: 80,
    uses: 5,
    multiplier: [5, 15, 10, 10, 10, 8, 5],
    color: 0xfaabac,
    image: 'rod-003',
    description: `For the awesome BALD gang only!\n_Anyone who has the \`BALD\` in their display name will get this rod!_`,
  },
]
